server:
  port: 8010

spring:
  application:
    name: biz-service
  datasource:
    url: jdbc:mysql://localhost:13306/seata_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
